const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log('languages array', languages);
const firstElement = 'the ' + 'first ' + 'element ' + 'of ' + 'the ' + 'array ' + 'is ' + languages[0];
console.log(firstElement);
const thirdElement = 'the ' + 'third ' + 'element ' + 'of ' + 'the ' + 'array ' + 'is ' + languages[2];
console.log(thirdElement);
const length = 'The ' + 'length ' + 'of ' + 'the ' + 'array ' + 'is ' + languages.length;
console.log(length);
const lastElement = 'The ' + 'last ' + 'element ' + 'of ' + 'the ' + 'array ' + 'is ' + languages[languages.length - 1];
console.log(lastElement);
